#ifndef CONFIG_H
#define CONFIG_H


#define GAME_TITLE "敬字寄媾 v1.0"
#define GAME_RES_PATH "./plane.rcc"
#define GAME_ICON ":/res/main_plane_0.png"
#define MAP_PATH ":/res/bg1.jpg"
#define MAP_SCROLL_SPEED 2

#define HERO_PATH ":/res/gra_planeImg2.png"
#define BULLET_PATH ":/res/bomb47.png"


#define ENEMYPLANENAME 1
#define PLAYERBULLETNAME 2
#define ENEMYBULLETNAME 3
#define BOMBNAME 4

#define SCENEWIDTH  1000
#define SCENEHEIGHT  1000
#define PLAYERPLANESIZE 40
#define FISHSIZE 100
#define BOSSSIZE 200
#define PLAYERBULLETSIZE 20
#define FISHBULLETSIZE1 20
#define FISHBULLETSIZE2 20
#define FISHBULLETSIZE3 20
#define BOSSBULLETSIZE1 80
#define BOSSBULLETWIDTH2 200
#define BOSSBULLETHEIGHT2 40
#define BOSSBULLETSIZE3 200
#define BOSSBULLETWIDTH4 200
#define BOSSBULLETHEIGHT4 200
#define BOMBSIZE 800


#define PLAYERPLANESPEED 10
#define FISHSPEED 10
#define BOSSSPEED 2
#define PLAYERBULLETSPEED 50
#define FISHBULLETSPEED1 20
#define FISHBULLETSPEED2 20
#define FISHBULLETSPEED3 20
#define BOSSBULLETSPEED1 5
#define BOSSBULLETSPEED2 20
#define BOSSBULLETSPEED3 20
#define BOSSBULLETSPEED4 5
#define BOMBSPEED 10

#define PLAYERPLANEBLOOD 3
#define PLAYERPLANEBOMB 3
#define PLAYERPLANEBULLET 3

#define FISHSCORE 10
#define BOSSSCORE 1000


！！！！！！！！！！！！！！！！



#endif // CONFIG_H
